-- Private application schema: clients access data through the authenticated Go API.
SET LOCAL search_path TO loop, pg_catalog;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dob DATE NOT NULL,
    avatar TEXT,
    nickname TEXT,
    about_me TEXT,
    isprivate SMALLINT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
, is_suspended SMALLINT NOT NULL DEFAULT 0, is_moderator SMALLINT NOT NULL DEFAULT 0);

CREATE TABLE followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT,
    image TEXT,
    privacy TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, image TEXT,
    FOREIGN KEY (post_id) REFERENCES posts(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(post_id, user_id)
);

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    creator_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE group_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role TEXT,
    status TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE group_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE group_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_time TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, creator_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (group_id) REFERENCES groups(id)
);

CREATE TABLE event_response_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    option_text TEXT NOT NULL,
    FOREIGN KEY (event_id) REFERENCES group_events(id)
);

CREATE TABLE event_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    response_option_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (event_id) REFERENCES group_events(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (response_option_id) REFERENCES event_response_options(id)
);

CREATE TABLE chats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user1_id BIGINT NOT NULL,
    user2_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user1_id) REFERENCES users(id),
    FOREIGN KEY (user2_id) REFERENCES users(id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    type TEXT DEFAULT 'text', is_read SMALLINT NOT NULL DEFAULT 0,
    FOREIGN KEY (chat_id) REFERENCES chats(id),
    FOREIGN KEY (sender_id) REFERENCES users(id)
);

CREATE TABLE group_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    from_user_id BIGINT,
    type TEXT NOT NULL,
    related_id BIGINT,
    content TEXT,
    status TEXT DEFAULT 'unread',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (from_user_id) REFERENCES users(id)
);

CREATE TABLE post_viewers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    viewer_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (viewer_id) REFERENCES users(id)
);

CREATE TABLE group_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    inviter_id BIGINT NOT NULL,
    invitee_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (inviter_id) REFERENCES users(id),
    FOREIGN KEY (invitee_id) REFERENCES users(id),
    UNIQUE(group_id, invitee_id)
);

CREATE TABLE group_join_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (group_id) REFERENCES groups(id),
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE(group_id, user_id)
);

CREATE TABLE group_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (post_id) REFERENCES group_posts(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE sessions (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    is_active SMALLINT NOT NULL DEFAULT 1,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP, auth_provider TEXT NOT NULL DEFAULT 'password',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE media_uploads(path TEXT PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE);

CREATE TABLE password_resets (
 token_hash TEXT PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 expires_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE user_blocks (
 blocker_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 blocked_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(blocker_id, blocked_id),
 CHECK(blocker_id != blocked_id)
);

CREATE TABLE reports (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 reporter_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
 target_type TEXT NOT NULL CHECK(target_type IN ('user','post','comment','group_post','group_comment','group_event')),
 target_id BIGINT NOT NULL,
 reason TEXT NOT NULL,
 status TEXT NOT NULL DEFAULT 'open' CHECK(status IN ('open','resolved','dismissed')),
 resolution TEXT NOT NULL DEFAULT '',
 resolved_by BIGINT REFERENCES users(id) ON DELETE SET NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 resolved_at TIMESTAMPTZ
);

CREATE TABLE user_ids(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);

CREATE TABLE oauth_identities (
 provider TEXT NOT NULL CHECK(provider='google'),
 subject TEXT NOT NULL,
 user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 PRIMARY KEY(provider, subject),
 UNIQUE(provider, user_id)
);

CREATE TABLE oauth_flows (
 token_hash TEXT PRIMARY KEY,
 verifier TEXT NOT NULL DEFAULT '',
 intent TEXT NOT NULL CHECK(intent IN ('signin','link','reauth','register')),
 user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
 subject TEXT NOT NULL DEFAULT '',
 email TEXT NOT NULL DEFAULT '',
 first_name TEXT NOT NULL DEFAULT '',
 last_name TEXT NOT NULL DEFAULT '',
 expires_at BIGINT NOT NULL
);

CREATE INDEX idx_sessions_user_id ON sessions(user_id);

CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);

CREATE INDEX messages_unread ON messages(chat_id, sender_id, is_read, id);

CREATE INDEX reports_status ON reports(status, id);

CREATE INDEX user_blocks_target ON user_blocks(blocked_id, blocker_id);

CREATE INDEX oauth_flows_expiry ON oauth_flows(expires_at);

CREATE UNIQUE INDEX sessions_one_active_user ON sessions(user_id) WHERE is_active=1;


-- Equivalent date and substring operations used by the SQLite query layer.
CREATE FUNCTION instr(text,text) RETURNS integer LANGUAGE sql IMMUTABLE STRICT SET search_path TO pg_catalog AS $$ SELECT strpos($1,$2) $$;
CREATE FUNCTION julianday(timestamptz) RETURNS numeric LANGUAGE sql IMMUTABLE STRICT SET search_path TO pg_catalog AS $$ SELECT extract(epoch FROM $1) $$;

CREATE TABLE rate_limits (
 scope TEXT NOT NULL, key_hash TEXT NOT NULL, tokens DOUBLE PRECISION NOT NULL,
 updated_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(scope,key_hash)
);
CREATE INDEX rate_limits_expiry ON rate_limits(updated_at);
CREATE FUNCTION take_rate_limit(scope_key text, client_key text, refill double precision, capacity double precision)
RETURNS integer LANGUAGE plpgsql SET search_path TO loop,pg_catalog AS $$
DECLARE available double precision; moment timestamptz := clock_timestamp(); last_update timestamptz;
BEGIN
 IF NOT EXISTS(SELECT 1 FROM rate_limits WHERE scope=scope_key AND key_hash=client_key) THEN
  PERFORM pg_advisory_xact_lock(hashtextextended(scope_key,72600421));
  IF (SELECT COUNT(*) FROM rate_limits WHERE scope=scope_key)>=10000 THEN RETURN 60; END IF;
 END IF;
 INSERT INTO rate_limits(scope,key_hash,tokens,updated_at) VALUES(scope_key,client_key,capacity,moment) ON CONFLICT DO NOTHING;
 SELECT tokens,updated_at INTO available,last_update FROM rate_limits WHERE scope=scope_key AND key_hash=client_key FOR UPDATE;
 moment := clock_timestamp();
 available := least(capacity, available + greatest(0,extract(epoch FROM moment-last_update))*refill);
 UPDATE rate_limits SET tokens=greatest(0,available-CASE WHEN available>=1 THEN 1 ELSE 0 END),updated_at=moment WHERE scope=scope_key AND key_hash=client_key;
 IF available<1 THEN RETURN greatest(1,ceil((1-available)/refill)::integer); END IF;
 RETURN 0;
END $$;
CREATE TABLE presence (connection_id TEXT PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL);
CREATE INDEX presence_expiry ON presence(expires_at);
CREATE INDEX presence_users ON presence(user_id,expires_at);


CREATE TABLE realtime_outbox(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,payload TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
